name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Lint: black
        run: |
          black --check .

      - name: Lint: isort
        run: |
          isort --check-only .

      - name: Lint: flake8
        run: |
          flake8

      - name: Type check: mypy
        run: |
          mypy .

      - name: Test with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q
